spring.application.name=exchkr
server.servlet.context-path=/exchkr
server.port=${PORT}

# JWT_SECRET
jwt.secret.key=${JWT_SECRET}

#DATABASE CONFIGURATION
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Enable Hibernate to log the SQL it executes
spring.jpa.show-sql=true

# Make the SQL logs easier to read
spring.jpa.properties.hibernate.format_sql=true

# Set the logging level for key components to DEBUG/TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.exchkr.club.management=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

app.security.cookie-secure=${COOKIE_SECURE}
app.frontend.cookie-domain=${FRONTEND_COOKIE_DOMAIN}

# Email Configuration
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.protocol=${SPRING_MAIL_PROTOCOL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#plaid config
plaid.clientID=${PLAID_CLIENT_ID}
plaid.secret=${PLAID_SECRET}
plaid.env=${PLAID_ENV}

plaid.webhookUrl=${PLAID_WEBHOOK_URL}

# Encryption Keys for Plaid Access Tokens
encryption.password=${PLAID_ENCRYPTION_PASSWORD}
encryption.salt=${PLAID_ENCRYPTION_SALT}

# Stripe secret key (sandbox/development)
stripe.api.secretKey=${STRIPE_API_SECRET_KEY}

# Stripe webhook secrets
stripe.webhook.secret.account=${STRIPE_WEBHOOK_SECRET_ACCOUNT}
stripe.webhook.secret.payment=${STRIPE_WEBHOOK_SECRET_PAYMENT}

app.frontend.base-url=${APP_FRONTEND_BASE_URL}
files.exchkr-dir=${FILE_UPLOAD_PATH}

# Platform fee in percentage
platform.fee.percentage=1

# Platform fee in dollar
platform.fee.dollar=0.30

# Stripe CARD fees
stripe.fee.card.percentage=2.9
stripe.fee.card.fixed=30

# Stripe ACH fees
stripe.fee.ach.percentage=0.8
stripe.fee.ach.max=50

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
