spring.application.name=exchkr
server.servlet.context-path=/exchkr

# Maps the secret key property name to an environment variable named JWT_SECRET
jwt.secret.key=${JWT_SECRET}

#DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/exchkr
spring.datasource.username=postgres
spring.datasource.password=Passw0rd
spring.jpa.hibernate.ddl-auto=update

# Enable Hibernate to log the SQL it executes
spring.jpa.show-sql=true

# Make the SQL logs easier to read
spring.jpa.properties.hibernate.format_sql=true

# Set the logging level for key components to DEBUG/TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework=DEBUG
logging.level.com.exchkr.club.management=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# We use HTTP locally, so the Secure flag must be FALSE.
app.security.cookie-secure=false

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yugdev.volkkommen@gmail.com
spring.mail.password=fgds zinn yypt qhod
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

#plaid config
plaid.clientID=694f87bc168aa50020a8a602
plaid.secret=cfcee55349760b123bd8adb21620a1
plaid.env=sandbox 

